# Generated by Django 5.0 on 2024-11-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_book', '0002_rename_client_address_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller')], default='seller', max_length=10),
        ),
    ]
